language: ruby

sudo: false

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head

before_install:
  - gem update --system
install: bundle install --path=vendor/bundle --retry=3 --jobs=3
cache:
  directories:
    - vendor/bundle

env:
  matrix:
    - "RAILS_VERSION=5.2.0"
    - "RAILS_VERSION=6.0.0"
    - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.7.0
  fast_finish: true
